### ISSUE TITLE
i have a issue .Can you help me

### ISSUE THREAD

**Issue by ArulPushpam** [IntuitDeveloper/HelloWorldApp-MVC5-Dotnet#2]
Hai,
  I have downloaded your package.b ut it's not working well .i will replace the client key, secret key and redirect URL in my webconfig.but it is not showing access token button. always show like this in my endpoint..

Callback
Code: none 
State: 8942b5ae05334c32ab415de6b0e5e91d (valid) 
RealmId: none 
Error: invalid_scope

**Comment by rkasaraneni20** [comment]
Hi ,  Can you please check what is the scope you provided and is your app connected to that scope?
